"""remove salt column

Revision ID: b58e1bcced97
Revises: 189f6ef6366b
Create Date: 2023-12-30 06:07:51.360426

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b58e1bcced97'
down_revision = '189f6ef6366b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'salt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('salt', sa.VARCHAR(length=256),
                  autoincrement=False, nullable=False, server_default='salt'))
    # ### end Alembic commands ###
