"""change author name unique param

Revision ID: debacc5f706a
Revises: 339bd6a50f75
Create Date: 2023-12-30 01:22:51.948356

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'debacc5f706a'
down_revision = '339bd6a50f75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authors', 'name',
                    existing_type=sa.VARCHAR(length=256),
                    nullable=False)
    op.create_unique_constraint(op.f('uq_authors_name'), 'authors', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_authors_name'), 'authors', type_='unique')
    op.alter_column('authors', 'name',
                    existing_type=sa.VARCHAR(length=256),
                    nullable=True)
    # ### end Alembic commands ###
