"""chage uniqu user model UniqueConstraint

Revision ID: 0179f0e9dca0
Revises: b58e1bcced97
Create Date: 2023-12-30 06:40:50.818867

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0179f0e9dca0'
down_revision = 'b58e1bcced97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
                    existing_type=sa.VARCHAR(length=256),
                    nullable=False)
    op.drop_constraint('uq_users_name_email', 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.create_unique_constraint('uq_users_name_email', 'users', ['name', 'email'])
    op.alter_column('users', 'email',
                    existing_type=sa.VARCHAR(length=256),
                    nullable=True)
    # ### end Alembic commands ###
