version: "3"

services:
  app:
    container_name: app
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ..:/workspace:cached

    command: sleep infinity
    env_file: .env

  db:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - bookshelf-data:/var/lib/postgresql/data
    env_file: .env

  web:
    container_name: web
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./web/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./web/ssl:/etc/nginx/ssl

volumes:
  bookshelf-data:
