class ExceptionMessage():

    INTERNAL_SERVER_ERROR = 'Internal Server Error'
    GOOGLE_BOOKS_API_HTTP_ERROR = 'HTTP error occurred'
    GOOGLE_BOOKS_API_UNEXPECTED_ERROR = 'Unexpected error occurred'
    GOOGLE_BOOKS_API_INVALID_RESPONSE = 'Invalid response received from the API'
    GOOGLE_BOOKS_API_IMAGE_DOWNLOAD_ERROR = 'Error downloading image from the API'
    DUPLICATE_USER = 'User already exists'
    INVALID_USER_EMAIL_FORMAT = 'Invalid user email format'
    USER_NOT_FOUND = 'User not found'
    INVALID_USER_PASSWORD = 'Invalid user password'
    INVALID_CREDENTIALS = 'Invalid credentials'
    NOT_ENOUGH_PERMISSIONS = 'Not enough permissions'
    BOOK_ISBN_DIGITS = 'ISBN must be 10 or 13 digits'
    BOOK_ISBN_FORMAT = 'ISBN must be numeric'
    DUPLICATE_BOOK_ISBN = 'Book already exists'
    USER_IS_NOT_VERIFIED = 'User is not verified'
    VERIFICATION_TOKEN_NOT_FOUND = 'Verification token not found'
